// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luewnstegrjsnlucdkja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZXduc3RlZ3Jqc25sdWNka2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4ODI0MTgsImV4cCI6MjA0OTQ1ODQxOH0.YZ-RRHV6c29pjb1KqhpkuRgM8eNIvI2HbYEhsf2P5xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);